version: "3.3"

services:


  postgres:
    image: postgres
    container_name: "postgresql"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  django:
    container_name: "django"
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    ports:
        - 80:8000
    depends_on: 
        - postgres
